version: '3.8'

services:
  voice-agent-backend:
    build: .
    container_name: united-voice-agent-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8000
      - SSL_ENABLED=false
      - LOG_LEVEL=INFO
      - MAX_CONNECTIONS=1000
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - voice-agent-network

  # Optional: Nginx proxy for production
  nginx:
    image: nginx:alpine
    container_name: united-voice-agent-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - voice-agent-backend
    restart: unless-stopped
    networks:
      - voice-agent-network

networks:
  voice-agent-network:
    driver: bridge

volumes:
  logs:
  temp: